#ifndef _ERROR_H
#define _ERROR_H

#define NO_ERROR 0
#define LEXICAL_ERROR 1
#define SYNTAX_ERROR 2
#define SEM_DEF_FUNC_ERROR 3
#define SEM_TYPE_ERROR 4
#define SEM_FUNC_ERROR 5
#define SEM_STMT_FUNC_ERROR 6
#define SEM_TYPE_COMP_ERROR 7
#define SEM_OTHER_ERROR 8
#define INTERNAL_ERROR 99

#endif // _ERROR_H